CLINICAL_DOCUMENTS = [
    {
        "id": "doc-01",
        "title": "Criterios de diabetes en adultos",
        "text": "Se considera diabetes cuando la glucosa en ayunas es mayor o igual a 126 mg/dL en dos mediciones o HbA1c mayor o igual a 6.5%.",
        "tags": ["diabetes", "glucosa", "hba1c"],
    },
    {
        "id": "doc-02",
        "title": "Prediabetes",
        "text": "La prediabetes se identifica con glucosa en ayunas entre 100 y 125 mg/dL o HbA1c entre 5.7% y 6.4%.",
        "tags": ["prediabetes", "glucosa", "hba1c"],
    },
    {
        "id": "doc-03",
        "title": "Hipertensión arterial",
        "text": "Hipertensión estadio 2 se define con presión arterial sistólica mayor o igual a 140 mmHg o diastólica mayor o igual a 90 mmHg.",
        "tags": ["hipertension", "presion arterial"],
    },
    {
        "id": "doc-04",
        "title": "Dislipidemia LDL",
        "text": "Un LDL mayor de 160 mg/dL incrementa riesgo cardiovascular en población general y requiere intervención según riesgo global.",
        "tags": ["ldl", "colesterol", "riesgo cardiovascular"],
    },
    {
        "id": "doc-05",
        "title": "Riesgo renal en diabetes",
        "text": "Microalbuminuria persistente y descenso de tasa de filtración glomerular sugieren nefropatía diabética temprana.",
        "tags": ["nefropatia", "albuminuria", "tfg"],
    },
    {
        "id": "doc-06",
        "title": "Tamizaje de retinopatía diabética",
        "text": "En diabetes tipo 2 se recomienda fondo de ojo al diagnóstico y luego control anual o según hallazgos.",
        "tags": ["retinopatia", "fondo de ojo"],
    },
    {
        "id": "doc-07",
        "title": "Obesidad e IMC",
        "text": "Un índice de masa corporal mayor o igual a 30 kg/m2 se clasifica como obesidad y aumenta riesgo metabólico.",
        "tags": ["imc", "obesidad"],
    },
    {
        "id": "doc-08",
        "title": "Síndrome metabólico",
        "text": "La presencia de obesidad abdominal, hipertensión, hiperglucemia y dislipidemia constituye síndrome metabólico.",
        "tags": ["sindrome metabolico", "riesgo"],
    },
    {
        "id": "doc-09",
        "title": "HbA1c objetivo",
        "text": "En adultos con diabetes, un objetivo frecuente de HbA1c es menor a 7%, individualizando según comorbilidades y edad.",
        "tags": ["hba1c", "control glucemico"],
    },
    {
        "id": "doc-10",
        "title": "Hipoglucemia",
        "text": "Se considera hipoglucemia cuando la glucosa capilar es menor a 70 mg/dL y requiere corrección inmediata.",
        "tags": ["hipoglucemia", "glucosa"],
    },
    {
        "id": "doc-11",
        "title": "Insuficiencia cardiaca y BNP",
        "text": "Valores elevados de BNP o NT-proBNP apoyan el diagnóstico de insuficiencia cardiaca en contexto clínico compatible.",
        "tags": ["bnp", "insuficiencia cardiaca"],
    },
    {
        "id": "doc-12",
        "title": "Triage sepsis",
        "text": "Sepsis probable cuando hay infección sospechada más disfunción orgánica, con lactato elevado y signos de hipoperfusión.",
        "tags": ["sepsis", "lactato"],
    },
    {
        "id": "doc-13",
        "title": "Enfermedad coronaria",
        "text": "Dolor torácico típico con troponina elevada y cambios electrocardiográficos orienta a síndrome coronario agudo.",
        "tags": ["troponina", "coronario", "ecg"],
    },
    {
        "id": "doc-14",
        "title": "Riesgo trombótico",
        "text": "Un dímero D elevado puede sugerir trombosis en escenarios de probabilidad clínica intermedia o alta.",
        "tags": ["dimero d", "trombosis"],
    },
    {
        "id": "doc-15",
        "title": "EPOC exacerbado",
        "text": "Aumento de disnea, volumen de esputo y purulencia son criterios clínicos de exacerbación de EPOC.",
        "tags": ["epoc", "disnea"],
    },
    {
        "id": "doc-16",
        "title": "Asma control",
        "text": "Asma no controlada se asocia a síntomas diurnos frecuentes, despertares nocturnos y uso repetido de rescate.",
        "tags": ["asma", "control"],
    },
    {
        "id": "doc-17",
        "title": "Riesgo de accidente cerebrovascular",
        "text": "Hipertensión, fibrilación auricular y diabetes aumentan de forma importante el riesgo de evento cerebrovascular.",
        "tags": ["acv", "fibrilacion auricular"],
    },
    {
        "id": "doc-18",
        "title": "Anemia ferropénica",
        "text": "Hemoglobina baja con ferritina disminuida sugiere anemia por déficit de hierro.",
        "tags": ["anemia", "ferritina"],
    },
    {
        "id": "doc-19",
        "title": "Función tiroidea",
        "text": "TSH elevada con T4 libre baja sugiere hipotiroidismo primario y requiere evaluación clínica integral.",
        "tags": ["tiroides", "tsh", "t4"],
    },
    {
        "id": "doc-20",
        "title": "Enfermedad hepática grasa",
        "text": "ALT y AST persistentemente elevadas en contexto metabólico pueden indicar hígado graso no alcohólico.",
        "tags": ["higado", "alt", "ast"],
    },
    {
        "id": "doc-21",
        "title": "Prevención cardiovascular",
        "text": "Control de presión arterial, glucosa y LDL junto con actividad física reduce eventos cardiovasculares mayores.",
        "tags": ["prevencion", "cardiovascular"],
    },
    {
        "id": "doc-22",
        "title": "Cuidado renal crónico",
        "text": "En enfermedad renal crónica se recomienda monitorizar creatinina, TFG y albuminuria de manera periódica.",
        "tags": ["renal", "creatinina", "albuminuria"],
    },
    {
        "id": "doc-23",
        "title": "Depresión del ST en ECG",
        "text": "Una depresión del segmento ST, cuantificada como oldpeak en el dataset UCI Heart Disease, se asocia con mayor probabilidad de isquemia miocárdica.",
        "tags": ["ecg", "oldpeak", "isquemia"],
    },
    {
        "id": "doc-24",
        "title": "Frecuencia máxima alcanzada",
        "text": "Un valor bajo de thalach (frecuencia cardiaca máxima) durante prueba de esfuerzo puede sugerir reserva cronotrópica limitada y mayor riesgo cardiovascular.",
        "tags": ["thalach", "prueba de esfuerzo", "riesgo cardiovascular"],
    },
    {
        "id": "doc-25",
        "title": "Dolor torácico y perfil clínico",
        "text": "El tipo de dolor torácico (cp) ayuda a estratificar riesgo de enfermedad coronaria; patrones atípicos o asintomáticos en población de riesgo requieren evaluación complementaria.",
        "tags": ["cp", "dolor toracico", "coronario"],
    },
    {
        "id": "doc-26",
        "title": "Carga aterosclerótica por angiografía",
        "text": "Un número mayor de vasos comprometidos (ca) se correlaciona con mayor severidad de enfermedad arterial coronaria y peor pronóstico clínico.",
        "tags": ["ca", "angiografia", "coronaria"],
    },
    {
        "id": "doc-27",
        "title": "Presión arterial en reposo",
        "text": "Trestbps elevado en combinación con colesterol alto y edad avanzada incrementa la probabilidad pretest de patología cardiovascular significativa.",
        "tags": ["trestbps", "presion arterial", "riesgo"],
    },
    {
        "id": "doc-28",
        "title": "Fenotipos de enfermedad cardiaca",
        "text": "En el objetivo num del dataset UCI, num=0 indica ausencia de enfermedad y num>=1 indica presencia con severidad creciente, útil para priorización clínica.",
        "tags": ["uci", "target", "severidad"],
    },
    {
        "id": "doc-29",
        "title": "Integración de datos para decisiones",
        "text": "La correlación entre hallazgos de ECG, observaciones FHIR y factores clínicos del paciente mejora la interpretabilidad en agentes RAG cardiológicos.",
        "tags": ["rag", "fhir", "ecg", "interpretabilidad"],
    },
    {
        "id": "doc-30",
        "title": "Triage de riesgo cardiaco",
        "text": "Pacientes con dolor torácico, cambios electrocardiográficos y biomarcadores anormales deben considerarse de alto riesgo y priorizar evaluación urgente.",
        "tags": ["triage", "ecg", "alto riesgo"],
    },
]