CLINICAL_DOCUMENTS = [
    {
        "id": "doc-01",
        "title": "Criterios de diabetes en adultos",
        "text": "Se considera diabetes cuando la glucosa en ayunas es mayor o igual a 126 mg/dL en dos mediciones o HbA1c mayor o igual a 6.5%.",
        "tags": ["diabetes", "glucosa", "hba1c"],
    },
    {
        "id": "doc-02",
        "title": "Prediabetes",
        "text": "La prediabetes se identifica con glucosa en ayunas entre 100 y 125 mg/dL o HbA1c entre 5.7% y 6.4%.",
        "tags": ["prediabetes", "glucosa", "hba1c"],
    },
    {
        "id": "doc-03",
        "title": "Hipertensión arterial",
        "text": "Hipertensión estadio 2 se define con presión arterial sistólica mayor o igual a 140 mmHg o diastólica mayor o igual a 90 mmHg.",
        "tags": ["hipertension", "presion arterial"],
    },
    {
        "id": "doc-04",
        "title": "Dislipidemia LDL",
        "text": "Un LDL mayor de 160 mg/dL incrementa riesgo cardiovascular en población general y requiere intervención según riesgo global.",
        "tags": ["ldl", "colesterol", "riesgo cardiovascular"],
    },
    {
        "id": "doc-05",
        "title": "Riesgo renal en diabetes",
        "text": "Microalbuminuria persistente y descenso de tasa de filtración glomerular sugieren nefropatía diabética temprana.",
        "tags": ["nefropatia", "albuminuria", "tfg"],
    },
    {
        "id": "doc-06",
        "title": "Tamizaje de retinopatía diabética",
        "text": "En diabetes tipo 2 se recomienda fondo de ojo al diagnóstico y luego control anual o según hallazgos.",
        "tags": ["retinopatia", "fondo de ojo"],
    },
    {
        "id": "doc-07",
        "title": "Obesidad e IMC",
        "text": "Un índice de masa corporal mayor o igual a 30 kg/m2 se clasifica como obesidad y aumenta riesgo metabólico.",
        "tags": ["imc", "obesidad"],
    },
    {
        "id": "doc-08",
        "title": "Síndrome metabólico",
        "text": "La presencia de obesidad abdominal, hipertensión, hiperglucemia y dislipidemia constituye síndrome metabólico.",
        "tags": ["sindrome metabolico", "riesgo"],
    },
    {
        "id": "doc-09",
        "title": "HbA1c objetivo",
        "text": "En adultos con diabetes, un objetivo frecuente de HbA1c es menor a 7%, individualizando según comorbilidades y edad.",
        "tags": ["hba1c", "control glucemico"],
    },
    {
        "id": "doc-10",
        "title": "Hipoglucemia",
        "text": "Se considera hipoglucemia cuando la glucosa capilar es menor a 70 mg/dL y requiere corrección inmediata.",
        "tags": ["hipoglucemia", "glucosa"],
    },
    {
        "id": "doc-11",
        "title": "Insuficiencia cardiaca y BNP",
        "text": "Valores elevados de BNP o NT-proBNP apoyan el diagnóstico de insuficiencia cardiaca en contexto clínico compatible.",
        "tags": ["bnp", "insuficiencia cardiaca"],
    },
    {
        "id": "doc-12",
        "title": "Triage sepsis",
        "text": "Sepsis probable cuando hay infección sospechada más disfunción orgánica, con lactato elevado y signos de hipoperfusión.",
        "tags": ["sepsis", "lactato"],
    },
    {
        "id": "doc-13",
        "title": "Enfermedad coronaria",
        "text": "Dolor torácico típico con troponina elevada y cambios electrocardiográficos orienta a síndrome coronario agudo.",
        "tags": ["troponina", "coronario", "ecg"],
    },
    {
        "id": "doc-14",
        "title": "Riesgo trombótico",
        "text": "Un dímero D elevado puede sugerir trombosis en escenarios de probabilidad clínica intermedia o alta.",
        "tags": ["dimero d", "trombosis"],
    },
    {
        "id": "doc-15",
        "title": "EPOC exacerbado",
        "text": "Aumento de disnea, volumen de esputo y purulencia son criterios clínicos de exacerbación de EPOC.",
        "tags": ["epoc", "disnea"],
    },
    {
        "id": "doc-16",
        "title": "Asma control",
        "text": "Asma no controlada se asocia a síntomas diurnos frecuentes, despertares nocturnos y uso repetido de rescate.",
        "tags": ["asma", "control"],
    },
    {
        "id": "doc-17",
        "title": "Riesgo de accidente cerebrovascular",
        "text": "Hipertensión, fibrilación auricular y diabetes aumentan de forma importante el riesgo de evento cerebrovascular.",
        "tags": ["acv", "fibrilacion auricular"],
    },
    {
        "id": "doc-18",
        "title": "Anemia ferropénica",
        "text": "Hemoglobina baja con ferritina disminuida sugiere anemia por déficit de hierro.",
        "tags": ["anemia", "ferritina"],
    },
    {
        "id": "doc-19",
        "title": "Función tiroidea",
        "text": "TSH elevada con T4 libre baja sugiere hipotiroidismo primario y requiere evaluación clínica integral.",
        "tags": ["tiroides", "tsh", "t4"],
    },
    {
        "id": "doc-20",
        "title": "Enfermedad hepática grasa",
        "text": "ALT y AST persistentemente elevadas en contexto metabólico pueden indicar hígado graso no alcohólico.",
        "tags": ["higado", "alt", "ast"],
    },
    {
        "id": "doc-21",
        "title": "Prevención cardiovascular",
        "text": "Control de presión arterial, glucosa y LDL junto con actividad física reduce eventos cardiovasculares mayores.",
        "tags": ["prevencion", "cardiovascular"],
    },
    {
        "id": "doc-22",
        "title": "Cuidado renal crónico",
        "text": "En enfermedad renal crónica se recomienda monitorizar creatinina, TFG y albuminuria de manera periódica.",
        "tags": ["renal", "creatinina", "albuminuria"],
    },
]